source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'WccyTaskTool_Example' do
  pod 'WccyTaskTool', :path => '../'

  target 'WccyTaskTool_Tests' do
    inherit! :search_paths

    
  end
end
